### ISSUE TITLE
Release milestone 2 build.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/moebius#294]
All of the initial release issues and problems should by now be addressed (See M2).
This milestone build should be published soon-ish, possibly after Mozilla's next sec cycle to pick up any sec bugs in one go.

- [x] Pick up FF58 sec bugs
- [x] Port sec patches to the release branch
- [x] Check for any outstanding blockers
- [x] Publish

**Comment by JustOff** [comment]
Please pay special attention to verify #232 on Linux, I have serious suspicions there is still a problem there.

**Comment by wolfbeast** [comment]
I have no way to verify this. looking at the code changes there simply shouldn't be an issue any longer when it comes to actual blocklist retrieval, parsing and application. The code simply isn't there to use anything but our own XML.

**Comment by JustOff** [comment]
I'm going to check this once RC build for Linux will be ready, but it would be nice if @trav90 also looked at it. [Here is the reason](https://forum.palemoon.org/viewtopic.php?p=131857#p131857) why I think the issue probably has not been solved yet.

**Comment by trav90** [comment]
A build from tip of master branch still intermittently displays the "is known to cause security or stability issues" message. Clicking on the more information link (regardless of the extension actually installed) it [displays a page](https://blocked.cdn.mozilla.net/i988.html) regarding Hero Fighter Community Toolbar, which coincidentally or not is also the [first entry](https://github.com/MoonchildProductions/moebius/blob/master/application/basilisk/app/blocklist.xml#L4) in Basilisk's blocklist.

**Comment by wolfbeast** [comment]
I'm completely at a loss here.

**Comment by wolfbeast** [comment]
Sec bug audit complete and relevant patches have been ported.

**Comment by trav90** [comment]
I think I have a lead on the add-ons/devtools problem on Linux. Up to this point I've been building Basilisk using the same compiler flags as I have for Pale Moon (which includes parallelization), and I think that this is causing the issues we've seen on Linux. A standard -O2 SSE2 optimized build seems to resolve these issues. Will be testing further and hopefully will have these 2 issues resolved for the M2 release.

@JustOff I will be sending you a PM on the forum shortly with a download link for this build if you are also able to test and confirm that'd be great!

**Comment by wolfbeast** [comment]
Ah-ha! That would explain because on Windows, I did not enable OpenMP on Basilisk when building (because I haven't looked at the impact of openmp-enabled libraries yet)

**Comment by JustOff** [comment]
Yes, I confirm the test build I received from @trav90 resolves both #232 and #197 issues :+1:

**Comment by trav90** [comment]
Awesome, thanks for verifying! I am going to consider both of issues resolved for M2.

**Comment by wolfbeast** [comment]
For point 3 I guess we need to build RCs to toss at a few people before I publish.

**Comment by JustOff** [comment]
Probably, we should also pick up [mfsa2018-05](https://www.mozilla.org/en-US/security/advisories/mfsa2018-05/) ([bug #1432966](https://bugzilla.mozilla.org/show_bug.cgi?id=1432966))?

**Comment by wolfbeast** [comment]
Basilisk has been published.
