### ISSUE TITLE
[META] Port Pale Moon to UXP

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/moebius#330]
This is the Meta bug for porting `Pale Moon` to `UXP`.

----

- [ ] Move application code to `UXP` in a branch (happening at `binoc-central/moebius-contrib`)
- [ ] Make `Pale Moon` Build
    - [ ] Basic `moz.build` changes
    - [ ] Basic `c++` changes
    - [ ] Fold `browsercomps` into libxul - [Bug 1302855](https://github.com/mozilla/gecko-dev/commit/032c476db630a13aa4b2a7e10e969d2632f17f10)
    - [ ] Use new XRE Wrapper in `nsBrowserApp.cpp` - _Mozilla Bug Numbers needed_
- [ ] Create `Tychokit` top level directory for `Tycho` versions of `Toolkit` components can live adjusting `Toolkit` build system to use `Tychokit` components if `MC_PALEMOON` is defined
    - [ ] Jetpack (`PMKit`)
    - [ ] DevTools
    - [ ] `Tycho` Add-ons Mananger
    - [ ] Possibly `Tycho` Sync
- [ ] Changes to front-end code to account for back-end changes
    - [ ] _To be determined_
- [ ] Fix Packaging and Windows Installer
- [ ] Merge `Pale Moon` onto `trunk`
